<header style="position: relative; width: 100%; overflow: hidden; background: #000;">
  <!-- Первый блок -->
  <div class="iHxmLe" jscontroller="yfZcPd" jsaction="rcuQ6b: npT2md" jsshadow="">
    <a class="rIRoqf" href="https://www.vijayavani.net/" aria-label="Видео…">
      <div class="gY2b2c">
        <div class="AZJdrc zGXzeb kCyj6d t7VAxe">
          <div class="uhHOwf BYbUcd" style="height:83px;width:148px">
            <img alt="" src="data:image/png;base64,...">
          </div>
          <div jsname="DwcXhb" class="LIna9b">
            <div jscontroller="Fy1Pv" class="VYkpsb" data-stfc="1" data-url="https://encrypted-vtbn0.gstatic.com/video?q=tbn:ANd9GcRRRPhLO5wn7F8sO5f0aCmJ6GPZhjqXR-CzNA">
              <video src="https://encrypted-vtbn0.gstatic.com/video?q=tbn:ANd9GcRRRPhLO5wn7F8sO5f0aCmJ6GPZhjqXR-CzNA" class="DqfBw" preload="auto" autoplay muted playsinline tabindex="-1" webkit-playsinline loop style="object-fit: cover; opacity: 1; width: 100%; height: 100%;"></video>
            </div>
          </div>
          <div class="Ylm8Fc kwKgNe" aria-hidden="true">
            <svg height="32" width="32" viewBox="0 0 32 32">
              <path class="MfcGr" d="M0 16C0 7.163 7.163 0 16 0s16 7.163 16 16-7.163 16-16 16S0 24.837 0 16Z"></path>
              <path class="Nci3Ge" d="M13 10.92v10.16a1 1 0 0 0 1.573.819l7.257-5.08a1 1 0 0 0 0-1.638l-7.256-5.08a1 1 0 0 0-1.574.82Z"></path>
            </svg>
          </div>
          <div class="kSFuOd rkqHyd"><span class="onyWef VbTyFc">Прямой эфир</span></div>
        </div>
      </div>
    </a>
  </div>

  <!-- Второй блок -->
  <div class="iHxmLe" jscontroller="yfZcPd" jsaction="rcuQ6b: npT2md" jsshadow="">
    <a class="rIRoqf" href="https://www.vijayavani.net/" aria-label="Видео…">
      <div class="gY2b2c">
        <div class="AZJdrc zGXzeb kCyj6d t7VAxe">
          <div class="uhHOwf BYbUcd" style="height:83px;width:148px">
            <img alt="" src="data:image/png;base64,...">
          </div>
          <div jsname="DwcXhb" class="LIna9b">
            <div jscontroller="Fy1Pv" class="VYkpsb" data-stfc="1" data-url="https://encrypted-vtbn0.gstatic.com/video?q=tbn:ANd9GcRRRPhLO5wn7F8sO5f0aCmJ6GPZhjqXR-CzNA">
              <video src="https://encrypted-vtbn0.gstatic.com/video?q=tbn:ANd9GcRRRPhLO5wn7F8sO5f0aCmJ6GPZhjqXR-CzNA" class="DqfBw" preload="auto" autoplay muted playsinline tabindex="-1" webkit-playsinline loop style="object-fit: cover; opacity: 1; width: 100%; height: 100%;"></video>
            </div>
          </div>
          <div class="Ylm8Fc kwKgNe" aria-hidden="true">
            <svg height="32" width="32" viewBox="0 0 32 32">
              <path class="MfcGr" d="M0 16C0 7.163 7.163 0 16 0s16 7.163 16 16-7.163 16-16 16S0 24.837 0 16Z"></path>
              <path class="Nci3Ge" d="M13 10.92v10.16a1 1 0 0 0 1.573.819l7.257-5.08a1 1 0 0 0 0-1.638l-7.256-5.08a1 1 0 0 0-1.574.82Z"></path>
            </svg>
          </div>
          <div class="kSFuOd rkqHyd"><span class="onyWef VbTyFc">Прямой эфир</span></div>
        </div>
      </div>
    </a>
  </div>
</header>
